FROM elixir:1.12-alpine

RUN mix local.hex --force
RUN mix local.rebar --force
WORKDIR /app

COPY mix.exs .
COPY mix.lock .

RUN mix deps.get
# RUN mix deps.get --only prod
COPY . .

RUN MIX_ENV=prod mix compile
RUN MIX_ENV=prod mix assets.deploy
# RUN mix do compile


# RUN mkdir assets

# COPY assets/package.json assets
# COPY assets/package-lock.json assets

CMD mix phx.server