version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ex_mink_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: 'postgres:13'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    command: mix phx.server
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ex_mink_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POOL_SIZE: "10"      
    # env_file:
    #   - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
volumes:
  pgdata: