apiVersion: apps/v1
kind: Deployment
metadata:
  name: elixir-app-deployment
  labels:
    app: elixir-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elixir-app
  template:
    metadata:
      labels:
        app: elixir-app 
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '4000'    
    spec:
      containers:
      - name: elixir-app
        image: cdesch/ex_mink:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4000     
        envFrom:
        - configMapRef:
            name: elixir-app-config          
        - secretRef:
            name: postgres-db-secret     
        - secretRef:
            name: elixir-app-secret          
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "350m"

          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
            failureThreshold: 1       