apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/pg-configmap.yaml
  - db/pg-service.yaml
  - db/pg-deployment.yaml
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: app-config
    literals:
      - APP_NAME=elixir-app