apiVersion: v1
kind: Service
metadata:
  name: elixir-app-service
spec:
  selector:
    app: elixir-app 
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
